// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKniGkDttuDhnkBVN5hCISWx9cWICmWAM',
    appId: '1:580203992579:android:3e205a7e95848bc75a6036',
    messagingSenderId: '580203992579',
    projectId: 'itaws-85a22',
    storageBucket: 'itaws-85a22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH8qGZR0MRnb2XflojDZzee9KDvM__gP0',
    appId: '1:580203992579:ios:ee6be893df79ad6f5a6036',
    messagingSenderId: '580203992579',
    projectId: 'itaws-85a22',
    storageBucket: 'itaws-85a22.appspot.com',
    iosClientId: '580203992579-t6t30khb3ia8hpuhcektbuuttl0keuha.apps.googleusercontent.com',
    iosBundleId: 'com.maantheme.maanFood',
  );
}
